[workspace]
resolver = "3"
members = ["apps/*", "crates/*"]
exclude = ["devices/lilygo_t_encoder_pro"]

[workspace.package]
edition = "2024"
repository = "https://github.com/NiltonVolpato/t-encoder"
publish = false

[workspace.dependencies]
slint = { version = "1.17.1", default-features = false, features = ["compat-1-2"] }
slint-build = { version = "1.17.1", features = ["experimental-module-builds"] }
theme = { path = "crates/theme", default-features = false }
