// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code, clippy::all)]
pub mod coprocessor_proto {

    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_PROVISIONING_STATE: u8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_PROVISIONING_STATE: u8 = 3;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_PROVISIONING_STATE: [ProvisioningState; 4] = [
        ProvisioningState::Inactive,
        ProvisioningState::Active,
        ProvisioningState::Provisioned,
        ProvisioningState::TimedOut,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct ProvisioningState(pub u8);
    #[allow(non_upper_case_globals)]
    impl ProvisioningState {
        pub const Inactive: Self = Self(0);
        pub const Active: Self = Self(1);
        pub const Provisioned: Self = Self(2);
        pub const TimedOut: Self = Self(3);

        pub const ENUM_MIN: u8 = 0;
        pub const ENUM_MAX: u8 = 3;
        pub const ENUM_VALUES: &'static [Self] =
            &[Self::Inactive, Self::Active, Self::Provisioned, Self::TimedOut];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::Inactive => Some("Inactive"),
                Self::Active => Some("Active"),
                Self::Provisioned => Some("Provisioned"),
                Self::TimedOut => Some("TimedOut"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for ProvisioningState {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for ProvisioningState {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for ProvisioningState {
        type Output = ProvisioningState;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for ProvisioningState {
        type Scalar = u8;
        #[inline]
        fn to_little_endian(self) -> u8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: u8) -> Self {
            let b = u8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for ProvisioningState {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            u8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for ProvisioningState {}
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_REQUEST: u8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_REQUEST: u8 = 5;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_REQUEST: [Request; 6] = [
        Request::NONE,
        Request::Heartbeat,
        Request::WifiConnectRequest,
        Request::StartProvisioning,
        Request::StopProvisioning,
        Request::StreamChunk,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct Request(pub u8);
    #[allow(non_upper_case_globals)]
    impl Request {
        pub const NONE: Self = Self(0);
        pub const Heartbeat: Self = Self(1);
        pub const WifiConnectRequest: Self = Self(2);
        pub const StartProvisioning: Self = Self(3);
        pub const StopProvisioning: Self = Self(4);
        pub const StreamChunk: Self = Self(5);

        pub const ENUM_MIN: u8 = 0;
        pub const ENUM_MAX: u8 = 5;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::NONE,
            Self::Heartbeat,
            Self::WifiConnectRequest,
            Self::StartProvisioning,
            Self::StopProvisioning,
            Self::StreamChunk,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::NONE => Some("NONE"),
                Self::Heartbeat => Some("Heartbeat"),
                Self::WifiConnectRequest => Some("WifiConnectRequest"),
                Self::StartProvisioning => Some("StartProvisioning"),
                Self::StopProvisioning => Some("StopProvisioning"),
                Self::StreamChunk => Some("StreamChunk"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for Request {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for Request {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for Request {
        type Output = Request;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for Request {
        type Scalar = u8;
        #[inline]
        fn to_little_endian(self) -> u8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: u8) -> Self {
            let b = u8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for Request {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            u8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for Request {}
    pub struct RequestUnionTableOffset {}

    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_RESPONSE: u8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_RESPONSE: u8 = 4;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_RESPONSE: [Response; 5] = [
        Response::NONE,
        Response::Heartbeat,
        Response::WifiStatus,
        Response::ProvisioningStatus,
        Response::StreamChunk,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct Response(pub u8);
    #[allow(non_upper_case_globals)]
    impl Response {
        pub const NONE: Self = Self(0);
        pub const Heartbeat: Self = Self(1);
        pub const WifiStatus: Self = Self(2);
        pub const ProvisioningStatus: Self = Self(3);
        pub const StreamChunk: Self = Self(4);

        pub const ENUM_MIN: u8 = 0;
        pub const ENUM_MAX: u8 = 4;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::NONE,
            Self::Heartbeat,
            Self::WifiStatus,
            Self::ProvisioningStatus,
            Self::StreamChunk,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::NONE => Some("NONE"),
                Self::Heartbeat => Some("Heartbeat"),
                Self::WifiStatus => Some("WifiStatus"),
                Self::ProvisioningStatus => Some("ProvisioningStatus"),
                Self::StreamChunk => Some("StreamChunk"),
                _ => None,
            }
        }
    }
    impl ::core::fmt::Debug for Response {
        fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> ::flatbuffers::Follow<'a> for Response {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
            Self(b)
        }
    }

    impl ::flatbuffers::Push for Response {
        type Output = Response;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
        }
    }

    impl ::flatbuffers::EndianScalar for Response {
        type Scalar = u8;
        #[inline]
        fn to_little_endian(self) -> u8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: u8) -> Self {
            let b = u8::from_le(v);
            Self(b)
        }
    }

    impl<'a> ::flatbuffers::Verifiable for Response {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            u8::run_verifier(v, pos)
        }
    }

    impl ::flatbuffers::SimpleToVerifyInSlice for Response {}
    pub struct ResponseUnionTableOffset {}

    pub enum WifiStatusOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct WifiStatus<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for WifiStatus<'a> {
        type Inner = WifiStatus<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> WifiStatus<'a> {
        pub const VT_CONNECTED: ::flatbuffers::VOffsetT = 4;
        pub const VT_IP: ::flatbuffers::VOffsetT = 6;
        pub const VT_SSID: ::flatbuffers::VOffsetT = 8;
        pub const VT_RSSI: ::flatbuffers::VOffsetT = 10;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            WifiStatus { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args WifiStatusArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<WifiStatus<'bldr>> {
            let mut builder = WifiStatusBuilder::new(_fbb);
            if let Some(x) = args.ssid {
                builder.add_ssid(x);
            }
            if let Some(x) = args.ip {
                builder.add_ip(x);
            }
            builder.add_rssi(args.rssi);
            builder.add_connected(args.connected);
            builder.finish()
        }

        #[inline]
        pub fn connected(&self) -> bool {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<bool>(WifiStatus::VT_CONNECTED, Some(false)).unwrap() }
        }
        #[inline]
        pub fn ip(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(WifiStatus::VT_IP, None)
            }
        }
        #[inline]
        pub fn ssid(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(WifiStatus::VT_SSID, None)
            }
        }
        #[inline]
        pub fn rssi(&self) -> i16 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<i16>(WifiStatus::VT_RSSI, Some(0)).unwrap() }
        }
    }

    impl ::flatbuffers::Verifiable for WifiStatus<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<bool>("connected", Self::VT_CONNECTED, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("ip", Self::VT_IP, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("ssid", Self::VT_SSID, false)?
                .visit_field::<i16>("rssi", Self::VT_RSSI, false)?
                .finish();
            Ok(())
        }
    }
    pub struct WifiStatusArgs<'a> {
        pub connected: bool,
        pub ip: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub ssid: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub rssi: i16,
    }
    impl<'a> Default for WifiStatusArgs<'a> {
        #[inline]
        fn default() -> Self {
            WifiStatusArgs { connected: false, ip: None, ssid: None, rssi: 0 }
        }
    }

    pub struct WifiStatusBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WifiStatusBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_connected(&mut self, connected: bool) {
            self.fbb_.push_slot::<bool>(WifiStatus::VT_CONNECTED, connected, false);
        }
        #[inline]
        pub fn add_ip(&mut self, ip: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(WifiStatus::VT_IP, ip);
        }
        #[inline]
        pub fn add_ssid(&mut self, ssid: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(WifiStatus::VT_SSID, ssid);
        }
        #[inline]
        pub fn add_rssi(&mut self, rssi: i16) {
            self.fbb_.push_slot::<i16>(WifiStatus::VT_RSSI, rssi, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> WifiStatusBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            WifiStatusBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<WifiStatus<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for WifiStatus<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("WifiStatus");
            ds.field("connected", &self.connected());
            ds.field("ip", &self.ip());
            ds.field("ssid", &self.ssid());
            ds.field("rssi", &self.rssi());
            ds.finish()
        }
    }
    pub enum WifiConnectRequestOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct WifiConnectRequest<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for WifiConnectRequest<'a> {
        type Inner = WifiConnectRequest<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> WifiConnectRequest<'a> {
        pub const VT_SSID: ::flatbuffers::VOffsetT = 4;
        pub const VT_PASSWORD: ::flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            WifiConnectRequest { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args WifiConnectRequestArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<WifiConnectRequest<'bldr>> {
            let mut builder = WifiConnectRequestBuilder::new(_fbb);
            if let Some(x) = args.password {
                builder.add_password(x);
            }
            if let Some(x) = args.ssid {
                builder.add_ssid(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn ssid(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(WifiConnectRequest::VT_SSID, None)
            }
        }
        #[inline]
        pub fn password(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(
                    WifiConnectRequest::VT_PASSWORD,
                    None,
                )
            }
        }
    }

    impl ::flatbuffers::Verifiable for WifiConnectRequest<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("ssid", Self::VT_SSID, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "password",
                    Self::VT_PASSWORD,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct WifiConnectRequestArgs<'a> {
        pub ssid: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub password: Option<::flatbuffers::WIPOffset<&'a str>>,
    }
    impl<'a> Default for WifiConnectRequestArgs<'a> {
        #[inline]
        fn default() -> Self {
            WifiConnectRequestArgs { ssid: None, password: None }
        }
    }

    pub struct WifiConnectRequestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> WifiConnectRequestBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_ssid(&mut self, ssid: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(WifiConnectRequest::VT_SSID, ssid);
        }
        #[inline]
        pub fn add_password(&mut self, password: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                WifiConnectRequest::VT_PASSWORD,
                password,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> WifiConnectRequestBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            WifiConnectRequestBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<WifiConnectRequest<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for WifiConnectRequest<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("WifiConnectRequest");
            ds.field("ssid", &self.ssid());
            ds.field("password", &self.password());
            ds.finish()
        }
    }
    pub enum HeartbeatOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct Heartbeat<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for Heartbeat<'a> {
        type Inner = Heartbeat<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> Heartbeat<'a> {
        pub const VT_UPTIME_MS: ::flatbuffers::VOffsetT = 4;
        pub const VT_HEAP_FREE: ::flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            Heartbeat { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args HeartbeatArgs,
        ) -> ::flatbuffers::WIPOffset<Heartbeat<'bldr>> {
            let mut builder = HeartbeatBuilder::new(_fbb);
            builder.add_uptime_ms(args.uptime_ms);
            builder.add_heap_free(args.heap_free);
            builder.finish()
        }

        #[inline]
        pub fn uptime_ms(&self) -> u64 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u64>(Heartbeat::VT_UPTIME_MS, Some(0)).unwrap() }
        }
        #[inline]
        pub fn heap_free(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(Heartbeat::VT_HEAP_FREE, Some(0)).unwrap() }
        }
    }

    impl ::flatbuffers::Verifiable for Heartbeat<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<u64>("uptime_ms", Self::VT_UPTIME_MS, false)?
                .visit_field::<u32>("heap_free", Self::VT_HEAP_FREE, false)?
                .finish();
            Ok(())
        }
    }
    pub struct HeartbeatArgs {
        pub uptime_ms: u64,
        pub heap_free: u32,
    }
    impl<'a> Default for HeartbeatArgs {
        #[inline]
        fn default() -> Self {
            HeartbeatArgs { uptime_ms: 0, heap_free: 0 }
        }
    }

    pub struct HeartbeatBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HeartbeatBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_uptime_ms(&mut self, uptime_ms: u64) {
            self.fbb_.push_slot::<u64>(Heartbeat::VT_UPTIME_MS, uptime_ms, 0);
        }
        #[inline]
        pub fn add_heap_free(&mut self, heap_free: u32) {
            self.fbb_.push_slot::<u32>(Heartbeat::VT_HEAP_FREE, heap_free, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> HeartbeatBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            HeartbeatBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<Heartbeat<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for Heartbeat<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("Heartbeat");
            ds.field("uptime_ms", &self.uptime_ms());
            ds.field("heap_free", &self.heap_free());
            ds.finish()
        }
    }
    pub enum StreamChunkOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct StreamChunk<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for StreamChunk<'a> {
        type Inner = StreamChunk<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> StreamChunk<'a> {
        pub const VT_STREAM_ID: ::flatbuffers::VOffsetT = 4;
        pub const VT_SEQUENCE: ::flatbuffers::VOffsetT = 6;
        pub const VT_IS_LAST: ::flatbuffers::VOffsetT = 8;
        pub const VT_PAYLOAD: ::flatbuffers::VOffsetT = 10;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            StreamChunk { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args StreamChunkArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<StreamChunk<'bldr>> {
            let mut builder = StreamChunkBuilder::new(_fbb);
            if let Some(x) = args.payload {
                builder.add_payload(x);
            }
            builder.add_sequence(args.sequence);
            builder.add_stream_id(args.stream_id);
            builder.add_is_last(args.is_last);
            builder.finish()
        }

        #[inline]
        pub fn stream_id(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(StreamChunk::VT_STREAM_ID, Some(0)).unwrap() }
        }
        #[inline]
        pub fn sequence(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(StreamChunk::VT_SEQUENCE, Some(0)).unwrap() }
        }
        #[inline]
        pub fn is_last(&self) -> bool {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<bool>(StreamChunk::VT_IS_LAST, Some(false)).unwrap() }
        }
        #[inline]
        pub fn payload(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                    StreamChunk::VT_PAYLOAD,
                    None,
                )
            }
        }
    }

    impl ::flatbuffers::Verifiable for StreamChunk<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<u32>("stream_id", Self::VT_STREAM_ID, false)?
                .visit_field::<u32>("sequence", Self::VT_SEQUENCE, false)?
                .visit_field::<bool>("is_last", Self::VT_IS_LAST, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                    "payload",
                    Self::VT_PAYLOAD,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct StreamChunkArgs<'a> {
        pub stream_id: u32,
        pub sequence: u32,
        pub is_last: bool,
        pub payload: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    }
    impl<'a> Default for StreamChunkArgs<'a> {
        #[inline]
        fn default() -> Self {
            StreamChunkArgs { stream_id: 0, sequence: 0, is_last: false, payload: None }
        }
    }

    pub struct StreamChunkBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> StreamChunkBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_stream_id(&mut self, stream_id: u32) {
            self.fbb_.push_slot::<u32>(StreamChunk::VT_STREAM_ID, stream_id, 0);
        }
        #[inline]
        pub fn add_sequence(&mut self, sequence: u32) {
            self.fbb_.push_slot::<u32>(StreamChunk::VT_SEQUENCE, sequence, 0);
        }
        #[inline]
        pub fn add_is_last(&mut self, is_last: bool) {
            self.fbb_.push_slot::<bool>(StreamChunk::VT_IS_LAST, is_last, false);
        }
        #[inline]
        pub fn add_payload(
            &mut self,
            payload: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
        ) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(StreamChunk::VT_PAYLOAD, payload);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> StreamChunkBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            StreamChunkBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<StreamChunk<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for StreamChunk<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("StreamChunk");
            ds.field("stream_id", &self.stream_id());
            ds.field("sequence", &self.sequence());
            ds.field("is_last", &self.is_last());
            ds.field("payload", &self.payload());
            ds.finish()
        }
    }
    pub enum StartProvisioningOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct StartProvisioning<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for StartProvisioning<'a> {
        type Inner = StartProvisioning<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> StartProvisioning<'a> {
        pub const VT_TIMEOUT_SECONDS: ::flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            StartProvisioning { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args StartProvisioningArgs,
        ) -> ::flatbuffers::WIPOffset<StartProvisioning<'bldr>> {
            let mut builder = StartProvisioningBuilder::new(_fbb);
            builder.add_timeout_seconds(args.timeout_seconds);
            builder.finish()
        }

        #[inline]
        pub fn timeout_seconds(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(StartProvisioning::VT_TIMEOUT_SECONDS, Some(0)).unwrap() }
        }
    }

    impl ::flatbuffers::Verifiable for StartProvisioning<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<u32>("timeout_seconds", Self::VT_TIMEOUT_SECONDS, false)?
                .finish();
            Ok(())
        }
    }
    pub struct StartProvisioningArgs {
        pub timeout_seconds: u32,
    }
    impl<'a> Default for StartProvisioningArgs {
        #[inline]
        fn default() -> Self {
            StartProvisioningArgs { timeout_seconds: 0 }
        }
    }

    pub struct StartProvisioningBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> StartProvisioningBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_timeout_seconds(&mut self, timeout_seconds: u32) {
            self.fbb_
                .push_slot::<u32>(StartProvisioning::VT_TIMEOUT_SECONDS, timeout_seconds, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> StartProvisioningBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            StartProvisioningBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<StartProvisioning<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for StartProvisioning<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("StartProvisioning");
            ds.field("timeout_seconds", &self.timeout_seconds());
            ds.finish()
        }
    }
    pub enum StopProvisioningOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct StopProvisioning<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for StopProvisioning<'a> {
        type Inner = StopProvisioning<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> StopProvisioning<'a> {
        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            StopProvisioning { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            _args: &'args StopProvisioningArgs,
        ) -> ::flatbuffers::WIPOffset<StopProvisioning<'bldr>> {
            let mut builder = StopProvisioningBuilder::new(_fbb);
            builder.finish()
        }
    }

    impl ::flatbuffers::Verifiable for StopProvisioning<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?.finish();
            Ok(())
        }
    }
    pub struct StopProvisioningArgs {}
    impl<'a> Default for StopProvisioningArgs {
        #[inline]
        fn default() -> Self {
            StopProvisioningArgs {}
        }
    }

    pub struct StopProvisioningBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> StopProvisioningBuilder<'a, 'b, A> {
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> StopProvisioningBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            StopProvisioningBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<StopProvisioning<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for StopProvisioning<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("StopProvisioning");
            ds.finish()
        }
    }
    pub enum ProvisioningStatusOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct ProvisioningStatus<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for ProvisioningStatus<'a> {
        type Inner = ProvisioningStatus<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> ProvisioningStatus<'a> {
        pub const VT_STATE: ::flatbuffers::VOffsetT = 4;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            ProvisioningStatus { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args ProvisioningStatusArgs,
        ) -> ::flatbuffers::WIPOffset<ProvisioningStatus<'bldr>> {
            let mut builder = ProvisioningStatusBuilder::new(_fbb);
            builder.add_state(args.state);
            builder.finish()
        }

        #[inline]
        pub fn state(&self) -> ProvisioningState {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<ProvisioningState>(
                        ProvisioningStatus::VT_STATE,
                        Some(ProvisioningState::Inactive),
                    )
                    .unwrap()
            }
        }
    }

    impl ::flatbuffers::Verifiable for ProvisioningStatus<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<ProvisioningState>("state", Self::VT_STATE, false)?
                .finish();
            Ok(())
        }
    }
    pub struct ProvisioningStatusArgs {
        pub state: ProvisioningState,
    }
    impl<'a> Default for ProvisioningStatusArgs {
        #[inline]
        fn default() -> Self {
            ProvisioningStatusArgs { state: ProvisioningState::Inactive }
        }
    }

    pub struct ProvisioningStatusBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ProvisioningStatusBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_state(&mut self, state: ProvisioningState) {
            self.fbb_.push_slot::<ProvisioningState>(
                ProvisioningStatus::VT_STATE,
                state,
                ProvisioningState::Inactive,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> ProvisioningStatusBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            ProvisioningStatusBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<ProvisioningStatus<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for ProvisioningStatus<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("ProvisioningStatus");
            ds.field("state", &self.state());
            ds.finish()
        }
    }
    pub enum RequestEnvelopeOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct RequestEnvelope<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for RequestEnvelope<'a> {
        type Inner = RequestEnvelope<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> RequestEnvelope<'a> {
        pub const VT_MESSAGE_TYPE: ::flatbuffers::VOffsetT = 4;
        pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            RequestEnvelope { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args RequestEnvelopeArgs,
        ) -> ::flatbuffers::WIPOffset<RequestEnvelope<'bldr>> {
            let mut builder = RequestEnvelopeBuilder::new(_fbb);
            if let Some(x) = args.message {
                builder.add_message(x);
            }
            builder.add_message_type(args.message_type);
            builder.finish()
        }

        #[inline]
        pub fn message_type(&self) -> Request {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<Request>(RequestEnvelope::VT_MESSAGE_TYPE, Some(Request::NONE))
                    .unwrap()
            }
        }
        #[inline]
        pub fn message(&self) -> Option<::flatbuffers::Table<'a>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(
                    RequestEnvelope::VT_MESSAGE,
                    None,
                )
            }
        }
        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_heartbeat(&self) -> Option<Heartbeat<'a>> {
            if self.message_type() == Request::Heartbeat {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { Heartbeat::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_wifi_connect_request(&self) -> Option<WifiConnectRequest<'a>> {
            if self.message_type() == Request::WifiConnectRequest {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { WifiConnectRequest::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_start_provisioning(&self) -> Option<StartProvisioning<'a>> {
            if self.message_type() == Request::StartProvisioning {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { StartProvisioning::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_stop_provisioning(&self) -> Option<StopProvisioning<'a>> {
            if self.message_type() == Request::StopProvisioning {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { StopProvisioning::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_stream_chunk(&self) -> Option<StreamChunk<'a>> {
            if self.message_type() == Request::StreamChunk {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { StreamChunk::init_from_table(t) }
                })
            } else {
                None
            }
        }
    }

    impl ::flatbuffers::Verifiable for RequestEnvelope<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
     .visit_union::<Request, _>("message_type", Self::VT_MESSAGE_TYPE, "message", Self::VT_MESSAGE, false, |key, v, pos| {
        match key {
          Request::Heartbeat => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Heartbeat>>("Request::Heartbeat", pos),
          Request::WifiConnectRequest => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<WifiConnectRequest>>("Request::WifiConnectRequest", pos),
          Request::StartProvisioning => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<StartProvisioning>>("Request::StartProvisioning", pos),
          Request::StopProvisioning => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<StopProvisioning>>("Request::StopProvisioning", pos),
          Request::StreamChunk => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<StreamChunk>>("Request::StreamChunk", pos),
          _ => Ok(()),
        }
     })?
     .finish();
            Ok(())
        }
    }
    pub struct RequestEnvelopeArgs {
        pub message_type: Request,
        pub message: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    }
    impl<'a> Default for RequestEnvelopeArgs {
        #[inline]
        fn default() -> Self {
            RequestEnvelopeArgs { message_type: Request::NONE, message: None }
        }
    }

    pub struct RequestEnvelopeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RequestEnvelopeBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_message_type(&mut self, message_type: Request) {
            self.fbb_.push_slot::<Request>(
                RequestEnvelope::VT_MESSAGE_TYPE,
                message_type,
                Request::NONE,
            );
        }
        #[inline]
        pub fn add_message(
            &mut self,
            message: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                RequestEnvelope::VT_MESSAGE,
                message,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> RequestEnvelopeBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            RequestEnvelopeBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<RequestEnvelope<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for RequestEnvelope<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("RequestEnvelope");
            ds.field("message_type", &self.message_type());
            match self.message_type() {
                Request::Heartbeat => {
                    if let Some(x) = self.message_as_heartbeat() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                Request::WifiConnectRequest => {
                    if let Some(x) = self.message_as_wifi_connect_request() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                Request::StartProvisioning => {
                    if let Some(x) = self.message_as_start_provisioning() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                Request::StopProvisioning => {
                    if let Some(x) = self.message_as_stop_provisioning() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                Request::StreamChunk => {
                    if let Some(x) = self.message_as_stream_chunk() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                _ => {
                    let x: Option<()> = None;
                    ds.field("message", &x)
                }
            };
            ds.finish()
        }
    }
    pub enum ResponseEnvelopeOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct ResponseEnvelope<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for ResponseEnvelope<'a> {
        type Inner = ResponseEnvelope<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
        }
    }

    impl<'a> ResponseEnvelope<'a> {
        pub const VT_MESSAGE_TYPE: ::flatbuffers::VOffsetT = 4;
        pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            ResponseEnvelope { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args ResponseEnvelopeArgs,
        ) -> ::flatbuffers::WIPOffset<ResponseEnvelope<'bldr>> {
            let mut builder = ResponseEnvelopeBuilder::new(_fbb);
            if let Some(x) = args.message {
                builder.add_message(x);
            }
            builder.add_message_type(args.message_type);
            builder.finish()
        }

        #[inline]
        pub fn message_type(&self) -> Response {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<Response>(ResponseEnvelope::VT_MESSAGE_TYPE, Some(Response::NONE))
                    .unwrap()
            }
        }
        #[inline]
        pub fn message(&self) -> Option<::flatbuffers::Table<'a>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(
                    ResponseEnvelope::VT_MESSAGE,
                    None,
                )
            }
        }
        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_heartbeat(&self) -> Option<Heartbeat<'a>> {
            if self.message_type() == Response::Heartbeat {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { Heartbeat::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_wifi_status(&self) -> Option<WifiStatus<'a>> {
            if self.message_type() == Response::WifiStatus {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { WifiStatus::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_provisioning_status(&self) -> Option<ProvisioningStatus<'a>> {
            if self.message_type() == Response::ProvisioningStatus {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { ProvisioningStatus::init_from_table(t) }
                })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn message_as_stream_chunk(&self) -> Option<StreamChunk<'a>> {
            if self.message_type() == Response::StreamChunk {
                self.message().map(|t| {
                    // Safety:
                    // Created from a valid Table for this object
                    // Which contains a valid union in this slot
                    unsafe { StreamChunk::init_from_table(t) }
                })
            } else {
                None
            }
        }
    }

    impl ::flatbuffers::Verifiable for ResponseEnvelope<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
     .visit_union::<Response, _>("message_type", Self::VT_MESSAGE_TYPE, "message", Self::VT_MESSAGE, false, |key, v, pos| {
        match key {
          Response::Heartbeat => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Heartbeat>>("Response::Heartbeat", pos),
          Response::WifiStatus => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<WifiStatus>>("Response::WifiStatus", pos),
          Response::ProvisioningStatus => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<ProvisioningStatus>>("Response::ProvisioningStatus", pos),
          Response::StreamChunk => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<StreamChunk>>("Response::StreamChunk", pos),
          _ => Ok(()),
        }
     })?
     .finish();
            Ok(())
        }
    }
    pub struct ResponseEnvelopeArgs {
        pub message_type: Response,
        pub message: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
    }
    impl<'a> Default for ResponseEnvelopeArgs {
        #[inline]
        fn default() -> Self {
            ResponseEnvelopeArgs { message_type: Response::NONE, message: None }
        }
    }

    pub struct ResponseEnvelopeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ResponseEnvelopeBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_message_type(&mut self, message_type: Response) {
            self.fbb_.push_slot::<Response>(
                ResponseEnvelope::VT_MESSAGE_TYPE,
                message_type,
                Response::NONE,
            );
        }
        #[inline]
        pub fn add_message(
            &mut self,
            message: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>,
        ) {
            self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                ResponseEnvelope::VT_MESSAGE,
                message,
            );
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> ResponseEnvelopeBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            ResponseEnvelopeBuilder { fbb_: _fbb, start_: start }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<ResponseEnvelope<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for ResponseEnvelope<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("ResponseEnvelope");
            ds.field("message_type", &self.message_type());
            match self.message_type() {
                Response::Heartbeat => {
                    if let Some(x) = self.message_as_heartbeat() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                Response::WifiStatus => {
                    if let Some(x) = self.message_as_wifi_status() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                Response::ProvisioningStatus => {
                    if let Some(x) = self.message_as_provisioning_status() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                Response::StreamChunk => {
                    if let Some(x) = self.message_as_stream_chunk() {
                        ds.field("message", &x)
                    } else {
                        ds.field(
                            "message",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                _ => {
                    let x: Option<()> = None;
                    ds.field("message", &x)
                }
            };
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `RequestEnvelope`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_request_envelope_unchecked`.
    pub fn root_as_request_envelope(
        buf: &[u8],
    ) -> Result<RequestEnvelope<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root::<RequestEnvelope>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `RequestEnvelope` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_request_envelope_unchecked`.
    pub fn size_prefixed_root_as_request_envelope(
        buf: &[u8],
    ) -> Result<RequestEnvelope<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root::<RequestEnvelope>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `RequestEnvelope` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_request_envelope_unchecked`.
    pub fn root_as_request_envelope_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<RequestEnvelope<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root_with_opts::<RequestEnvelope<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `RequestEnvelope` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_request_envelope_unchecked`.
    pub fn size_prefixed_root_as_request_envelope_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<RequestEnvelope<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root_with_opts::<RequestEnvelope<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a RequestEnvelope and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `RequestEnvelope`.
    pub unsafe fn root_as_request_envelope_unchecked(buf: &[u8]) -> RequestEnvelope<'_> {
        unsafe { ::flatbuffers::root_unchecked::<RequestEnvelope>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed RequestEnvelope and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `RequestEnvelope`.
    pub unsafe fn size_prefixed_root_as_request_envelope_unchecked(
        buf: &[u8],
    ) -> RequestEnvelope<'_> {
        unsafe { ::flatbuffers::size_prefixed_root_unchecked::<RequestEnvelope>(buf) }
    }
    #[inline]
    pub fn finish_request_envelope_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<RequestEnvelope<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_request_envelope_buffer<
        'a,
        'b,
        A: ::flatbuffers::Allocator + 'a,
    >(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<RequestEnvelope<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod CoprocessorProto
