[package]
name = "app-launcher"
links = "app_launcher"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "launcher-simulator"
path = "src/bin/main.rs"

[features]
default = ["apps", "simulator"]
apps = [
    "dep:app-clock",
    "dep:app-pomodoro",
    "dep:app-macropad",
    "dep:app-simon",
    "dep:app-magic8",
    "dep:app-sonos",
]
simulator = [
    "slint/renderer-software",
    "slint/software-renderer-path",
    "slint/backend-winit",
    "slint/std",
    "slint/mcp",
    "theme/std",
    "app-clock?/simulator",
    "app-pomodoro?/simulator",
    "app-macropad?/simulator",
    "app-simon?/simulator",
    "app-magic8?/simulator",
    "app-sonos?/simulator",
]

[dependencies]
slint = { workspace = true }
theme = { workspace = true }
app-clock = { path = "../clock", default-features = false, optional = true }
app-pomodoro = { path = "../pomodoro", default-features = false, optional = true }
app-macropad = { path = "../macropad", default-features = false, optional = true }
app-simon = { path = "../simon", default-features = false, optional = true }
app-magic8 = { path = "../magic8", default-features = false, optional = true }
app-sonos = { path = "../sonos", default-features = false, optional = true }

[dev-dependencies]
slint = { workspace = true }

[build-dependencies]
baker = { workspace = true }
