[package]
name = "app-launcher"
links = "app_launcher"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "launcher-simulator"
path = "src/bin/main.rs"

[features]
default = ["simulator"]
simulator = [
    "slint/renderer-software",
    "slint/software-renderer-path",
    "slint/backend-winit",
    "slint/std",
    "slint/mcp",
    "theme/std",
    "app-clock/simulator",
    "app-clock2/simulator",
]

[dependencies]
slint = { workspace = true }
theme = { workspace = true }
app-clock = { path = "../clock", default-features = false }
app-clock2 = { path = "../clock2", default-features = false }

[build-dependencies]
slint-build = { workspace = true }
