[package]
name = "theme"
links = "theme"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
    "slint/renderer-software",
    "slint/software-renderer-path",
    "slint/backend-winit",
    "slint/std",
    "slint/mcp",
]

[dependencies]
slint = { workspace = true }

[build-dependencies]
baker = { workspace = true }
