// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COPROCESSOR_COPROCESSORPROTO_H_
#define FLATBUFFERS_GENERATED_COPROCESSOR_COPROCESSORPROTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace CoprocessorProto {

struct WifiStatus;
struct WifiStatusBuilder;

struct WifiConnectRequest;
struct WifiConnectRequestBuilder;

struct Heartbeat;
struct HeartbeatBuilder;

struct StreamChunk;
struct StreamChunkBuilder;

struct StartProvisioning;
struct StartProvisioningBuilder;

struct StopProvisioning;
struct StopProvisioningBuilder;

struct ProvisioningStatus;
struct ProvisioningStatusBuilder;

struct Hello;
struct HelloBuilder;

struct TimeSync;
struct TimeSyncBuilder;

struct RequestEnvelope;
struct RequestEnvelopeBuilder;

struct ResponseEnvelope;
struct ResponseEnvelopeBuilder;

enum ProvisioningState : uint8_t {
  ProvisioningState_Inactive = 0,
  ProvisioningState_Active = 1,
  ProvisioningState_Provisioned = 2,
  ProvisioningState_TimedOut = 3,
  ProvisioningState_MIN = ProvisioningState_Inactive,
  ProvisioningState_MAX = ProvisioningState_TimedOut
};

inline const ProvisioningState (&EnumValuesProvisioningState())[4] {
  static const ProvisioningState values[] = {
    ProvisioningState_Inactive,
    ProvisioningState_Active,
    ProvisioningState_Provisioned,
    ProvisioningState_TimedOut
  };
  return values;
}

inline const char * const *EnumNamesProvisioningState() {
  static const char * const names[5] = {
    "Inactive",
    "Active",
    "Provisioned",
    "TimedOut",
    nullptr
  };
  return names;
}

inline const char *EnumNameProvisioningState(ProvisioningState e) {
  if (::flatbuffers::IsOutRange(e, ProvisioningState_Inactive, ProvisioningState_TimedOut)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesProvisioningState()[index];
}

enum Request : uint8_t {
  Request_NONE = 0,
  Request_Heartbeat = 1,
  Request_WifiConnectRequest = 2,
  Request_StartProvisioning = 3,
  Request_StopProvisioning = 4,
  Request_StreamChunk = 5,
  Request_Hello = 6,
  Request_MIN = Request_NONE,
  Request_MAX = Request_Hello
};

inline const Request (&EnumValuesRequest())[7] {
  static const Request values[] = {
    Request_NONE,
    Request_Heartbeat,
    Request_WifiConnectRequest,
    Request_StartProvisioning,
    Request_StopProvisioning,
    Request_StreamChunk,
    Request_Hello
  };
  return values;
}

inline const char * const *EnumNamesRequest() {
  static const char * const names[8] = {
    "NONE",
    "Heartbeat",
    "WifiConnectRequest",
    "StartProvisioning",
    "StopProvisioning",
    "StreamChunk",
    "Hello",
    nullptr
  };
  return names;
}

inline const char *EnumNameRequest(Request e) {
  if (::flatbuffers::IsOutRange(e, Request_NONE, Request_Hello)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRequest()[index];
}

template<typename T> struct RequestTraits {
  static const Request enum_value = Request_NONE;
};

template<> struct RequestTraits<CoprocessorProto::Heartbeat> {
  static const Request enum_value = Request_Heartbeat;
};

template<> struct RequestTraits<CoprocessorProto::WifiConnectRequest> {
  static const Request enum_value = Request_WifiConnectRequest;
};

template<> struct RequestTraits<CoprocessorProto::StartProvisioning> {
  static const Request enum_value = Request_StartProvisioning;
};

template<> struct RequestTraits<CoprocessorProto::StopProvisioning> {
  static const Request enum_value = Request_StopProvisioning;
};

template<> struct RequestTraits<CoprocessorProto::StreamChunk> {
  static const Request enum_value = Request_StreamChunk;
};

template<> struct RequestTraits<CoprocessorProto::Hello> {
  static const Request enum_value = Request_Hello;
};

template <bool B = false>
bool VerifyRequest(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Request type);
template <bool B = false>
bool VerifyRequestVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum Response : uint8_t {
  Response_NONE = 0,
  Response_Heartbeat = 1,
  Response_WifiStatus = 2,
  Response_ProvisioningStatus = 3,
  Response_StreamChunk = 4,
  Response_Hello = 5,
  Response_TimeSync = 6,
  Response_MIN = Response_NONE,
  Response_MAX = Response_TimeSync
};

inline const Response (&EnumValuesResponse())[7] {
  static const Response values[] = {
    Response_NONE,
    Response_Heartbeat,
    Response_WifiStatus,
    Response_ProvisioningStatus,
    Response_StreamChunk,
    Response_Hello,
    Response_TimeSync
  };
  return values;
}

inline const char * const *EnumNamesResponse() {
  static const char * const names[8] = {
    "NONE",
    "Heartbeat",
    "WifiStatus",
    "ProvisioningStatus",
    "StreamChunk",
    "Hello",
    "TimeSync",
    nullptr
  };
  return names;
}

inline const char *EnumNameResponse(Response e) {
  if (::flatbuffers::IsOutRange(e, Response_NONE, Response_TimeSync)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResponse()[index];
}

template<typename T> struct ResponseTraits {
  static const Response enum_value = Response_NONE;
};

template<> struct ResponseTraits<CoprocessorProto::Heartbeat> {
  static const Response enum_value = Response_Heartbeat;
};

template<> struct ResponseTraits<CoprocessorProto::WifiStatus> {
  static const Response enum_value = Response_WifiStatus;
};

template<> struct ResponseTraits<CoprocessorProto::ProvisioningStatus> {
  static const Response enum_value = Response_ProvisioningStatus;
};

template<> struct ResponseTraits<CoprocessorProto::StreamChunk> {
  static const Response enum_value = Response_StreamChunk;
};

template<> struct ResponseTraits<CoprocessorProto::Hello> {
  static const Response enum_value = Response_Hello;
};

template<> struct ResponseTraits<CoprocessorProto::TimeSync> {
  static const Response enum_value = Response_TimeSync;
};

template <bool B = false>
bool VerifyResponse(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Response type);
template <bool B = false>
bool VerifyResponseVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct WifiStatus FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WifiStatusBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONNECTED = 4,
    VT_IP = 6,
    VT_SSID = 8,
    VT_RSSI = 10
  };
  bool connected() const {
    return GetField<uint8_t>(VT_CONNECTED, 0) != 0;
  }
  const ::flatbuffers::String *ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IP);
  }
  const ::flatbuffers::String *ssid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SSID);
  }
  int16_t rssi() const {
    return GetField<int16_t>(VT_RSSI, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CONNECTED, 1) &&
           VerifyOffset(verifier, VT_IP) &&
           verifier.VerifyString(ip()) &&
           VerifyOffset(verifier, VT_SSID) &&
           verifier.VerifyString(ssid()) &&
           VerifyField<int16_t>(verifier, VT_RSSI, 2) &&
           verifier.EndTable();
  }
};

struct WifiStatusBuilder {
  typedef WifiStatus Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_connected(bool connected) {
    fbb_.AddElement<uint8_t>(WifiStatus::VT_CONNECTED, static_cast<uint8_t>(connected), 0);
  }
  void add_ip(::flatbuffers::Offset<::flatbuffers::String> ip) {
    fbb_.AddOffset(WifiStatus::VT_IP, ip);
  }
  void add_ssid(::flatbuffers::Offset<::flatbuffers::String> ssid) {
    fbb_.AddOffset(WifiStatus::VT_SSID, ssid);
  }
  void add_rssi(int16_t rssi) {
    fbb_.AddElement<int16_t>(WifiStatus::VT_RSSI, rssi, 0);
  }
  explicit WifiStatusBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WifiStatus> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WifiStatus>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WifiStatus> CreateWifiStatus(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool connected = false,
    ::flatbuffers::Offset<::flatbuffers::String> ip = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ssid = 0,
    int16_t rssi = 0) {
  WifiStatusBuilder builder_(_fbb);
  builder_.add_ssid(ssid);
  builder_.add_ip(ip);
  builder_.add_rssi(rssi);
  builder_.add_connected(connected);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WifiStatus> CreateWifiStatusDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool connected = false,
    const char *ip = nullptr,
    const char *ssid = nullptr,
    int16_t rssi = 0) {
  auto ip__ = ip ? _fbb.CreateString(ip) : 0;
  auto ssid__ = ssid ? _fbb.CreateString(ssid) : 0;
  return CoprocessorProto::CreateWifiStatus(
      _fbb,
      connected,
      ip__,
      ssid__,
      rssi);
}

struct WifiConnectRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WifiConnectRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SSID = 4,
    VT_PASSWORD = 6
  };
  const ::flatbuffers::String *ssid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SSID);
  }
  const ::flatbuffers::String *password() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PASSWORD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SSID) &&
           verifier.VerifyString(ssid()) &&
           VerifyOffset(verifier, VT_PASSWORD) &&
           verifier.VerifyString(password()) &&
           verifier.EndTable();
  }
};

struct WifiConnectRequestBuilder {
  typedef WifiConnectRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ssid(::flatbuffers::Offset<::flatbuffers::String> ssid) {
    fbb_.AddOffset(WifiConnectRequest::VT_SSID, ssid);
  }
  void add_password(::flatbuffers::Offset<::flatbuffers::String> password) {
    fbb_.AddOffset(WifiConnectRequest::VT_PASSWORD, password);
  }
  explicit WifiConnectRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WifiConnectRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WifiConnectRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WifiConnectRequest> CreateWifiConnectRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> ssid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> password = 0) {
  WifiConnectRequestBuilder builder_(_fbb);
  builder_.add_password(password);
  builder_.add_ssid(ssid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WifiConnectRequest> CreateWifiConnectRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *ssid = nullptr,
    const char *password = nullptr) {
  auto ssid__ = ssid ? _fbb.CreateString(ssid) : 0;
  auto password__ = password ? _fbb.CreateString(password) : 0;
  return CoprocessorProto::CreateWifiConnectRequest(
      _fbb,
      ssid__,
      password__);
}

struct Heartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UPTIME_MS = 4,
    VT_HEAP_FREE = 6
  };
  uint64_t uptime_ms() const {
    return GetField<uint64_t>(VT_UPTIME_MS, 0);
  }
  uint32_t heap_free() const {
    return GetField<uint32_t>(VT_HEAP_FREE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_UPTIME_MS, 8) &&
           VerifyField<uint32_t>(verifier, VT_HEAP_FREE, 4) &&
           verifier.EndTable();
  }
};

struct HeartbeatBuilder {
  typedef Heartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uptime_ms(uint64_t uptime_ms) {
    fbb_.AddElement<uint64_t>(Heartbeat::VT_UPTIME_MS, uptime_ms, 0);
  }
  void add_heap_free(uint32_t heap_free) {
    fbb_.AddElement<uint32_t>(Heartbeat::VT_HEAP_FREE, heap_free, 0);
  }
  explicit HeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Heartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Heartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Heartbeat> CreateHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t uptime_ms = 0,
    uint32_t heap_free = 0) {
  HeartbeatBuilder builder_(_fbb);
  builder_.add_uptime_ms(uptime_ms);
  builder_.add_heap_free(heap_free);
  return builder_.Finish();
}

struct StreamChunk FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StreamChunkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STREAM_ID = 4,
    VT_SEQUENCE = 6,
    VT_IS_LAST = 8,
    VT_PAYLOAD = 10
  };
  uint32_t stream_id() const {
    return GetField<uint32_t>(VT_STREAM_ID, 0);
  }
  uint32_t sequence() const {
    return GetField<uint32_t>(VT_SEQUENCE, 0);
  }
  bool is_last() const {
    return GetField<uint8_t>(VT_IS_LAST, 0) != 0;
  }
  const ::flatbuffers::Vector<uint8_t> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PAYLOAD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_STREAM_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_SEQUENCE, 4) &&
           VerifyField<uint8_t>(verifier, VT_IS_LAST, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.EndTable();
  }
};

struct StreamChunkBuilder {
  typedef StreamChunk Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_stream_id(uint32_t stream_id) {
    fbb_.AddElement<uint32_t>(StreamChunk::VT_STREAM_ID, stream_id, 0);
  }
  void add_sequence(uint32_t sequence) {
    fbb_.AddElement<uint32_t>(StreamChunk::VT_SEQUENCE, sequence, 0);
  }
  void add_is_last(bool is_last) {
    fbb_.AddElement<uint8_t>(StreamChunk::VT_IS_LAST, static_cast<uint8_t>(is_last), 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload) {
    fbb_.AddOffset(StreamChunk::VT_PAYLOAD, payload);
  }
  explicit StreamChunkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StreamChunk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StreamChunk>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StreamChunk> CreateStreamChunk(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t stream_id = 0,
    uint32_t sequence = 0,
    bool is_last = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload = 0) {
  StreamChunkBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_sequence(sequence);
  builder_.add_stream_id(stream_id);
  builder_.add_is_last(is_last);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StreamChunk> CreateStreamChunkDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t stream_id = 0,
    uint32_t sequence = 0,
    bool is_last = false,
    const std::vector<uint8_t> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<uint8_t>(*payload) : 0;
  return CoprocessorProto::CreateStreamChunk(
      _fbb,
      stream_id,
      sequence,
      is_last,
      payload__);
}

struct StartProvisioning FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartProvisioningBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMEOUT_SECONDS = 4
  };
  uint32_t timeout_seconds() const {
    return GetField<uint32_t>(VT_TIMEOUT_SECONDS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TIMEOUT_SECONDS, 4) &&
           verifier.EndTable();
  }
};

struct StartProvisioningBuilder {
  typedef StartProvisioning Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timeout_seconds(uint32_t timeout_seconds) {
    fbb_.AddElement<uint32_t>(StartProvisioning::VT_TIMEOUT_SECONDS, timeout_seconds, 0);
  }
  explicit StartProvisioningBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartProvisioning> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartProvisioning>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StartProvisioning> CreateStartProvisioning(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t timeout_seconds = 0) {
  StartProvisioningBuilder builder_(_fbb);
  builder_.add_timeout_seconds(timeout_seconds);
  return builder_.Finish();
}

struct StopProvisioning FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StopProvisioningBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct StopProvisioningBuilder {
  typedef StopProvisioning Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit StopProvisioningBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StopProvisioning> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StopProvisioning>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StopProvisioning> CreateStopProvisioning(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  StopProvisioningBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ProvisioningStatus FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProvisioningStatusBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATE = 4
  };
  CoprocessorProto::ProvisioningState state() const {
    return static_cast<CoprocessorProto::ProvisioningState>(GetField<uint8_t>(VT_STATE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_STATE, 1) &&
           verifier.EndTable();
  }
};

struct ProvisioningStatusBuilder {
  typedef ProvisioningStatus Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_state(CoprocessorProto::ProvisioningState state) {
    fbb_.AddElement<uint8_t>(ProvisioningStatus::VT_STATE, static_cast<uint8_t>(state), 0);
  }
  explicit ProvisioningStatusBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ProvisioningStatus> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ProvisioningStatus>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ProvisioningStatus> CreateProvisioningStatus(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    CoprocessorProto::ProvisioningState state = CoprocessorProto::ProvisioningState_Inactive) {
  ProvisioningStatusBuilder builder_(_fbb);
  builder_.add_state(state);
  return builder_.Finish();
}

struct Hello FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HelloBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct HelloBuilder {
  typedef Hello Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit HelloBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Hello> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Hello>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Hello> CreateHello(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  HelloBuilder builder_(_fbb);
  return builder_.Finish();
}

struct TimeSync FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TimeSyncBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EPOCH_SECONDS = 4,
    VT_SUBSEC_MICROS = 6
  };
  uint64_t epoch_seconds() const {
    return GetField<uint64_t>(VT_EPOCH_SECONDS, 0);
  }
  uint32_t subsec_micros() const {
    return GetField<uint32_t>(VT_SUBSEC_MICROS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_EPOCH_SECONDS, 8) &&
           VerifyField<uint32_t>(verifier, VT_SUBSEC_MICROS, 4) &&
           verifier.EndTable();
  }
};

struct TimeSyncBuilder {
  typedef TimeSync Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_epoch_seconds(uint64_t epoch_seconds) {
    fbb_.AddElement<uint64_t>(TimeSync::VT_EPOCH_SECONDS, epoch_seconds, 0);
  }
  void add_subsec_micros(uint32_t subsec_micros) {
    fbb_.AddElement<uint32_t>(TimeSync::VT_SUBSEC_MICROS, subsec_micros, 0);
  }
  explicit TimeSyncBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TimeSync> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TimeSync>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TimeSync> CreateTimeSync(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t epoch_seconds = 0,
    uint32_t subsec_micros = 0) {
  TimeSyncBuilder builder_(_fbb);
  builder_.add_epoch_seconds(epoch_seconds);
  builder_.add_subsec_micros(subsec_micros);
  return builder_.Finish();
}

struct RequestEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RequestEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE_TYPE = 4,
    VT_MESSAGE = 6
  };
  CoprocessorProto::Request message_type() const {
    return static_cast<CoprocessorProto::Request>(GetField<uint8_t>(VT_MESSAGE_TYPE, 0));
  }
  const void *message() const {
    return GetPointer<const void *>(VT_MESSAGE);
  }
  template<typename T> const T *message_as() const;
  const CoprocessorProto::Heartbeat *message_as_Heartbeat() const {
    return message_type() == CoprocessorProto::Request_Heartbeat ? static_cast<const CoprocessorProto::Heartbeat *>(message()) : nullptr;
  }
  const CoprocessorProto::WifiConnectRequest *message_as_WifiConnectRequest() const {
    return message_type() == CoprocessorProto::Request_WifiConnectRequest ? static_cast<const CoprocessorProto::WifiConnectRequest *>(message()) : nullptr;
  }
  const CoprocessorProto::StartProvisioning *message_as_StartProvisioning() const {
    return message_type() == CoprocessorProto::Request_StartProvisioning ? static_cast<const CoprocessorProto::StartProvisioning *>(message()) : nullptr;
  }
  const CoprocessorProto::StopProvisioning *message_as_StopProvisioning() const {
    return message_type() == CoprocessorProto::Request_StopProvisioning ? static_cast<const CoprocessorProto::StopProvisioning *>(message()) : nullptr;
  }
  const CoprocessorProto::StreamChunk *message_as_StreamChunk() const {
    return message_type() == CoprocessorProto::Request_StreamChunk ? static_cast<const CoprocessorProto::StreamChunk *>(message()) : nullptr;
  }
  const CoprocessorProto::Hello *message_as_Hello() const {
    return message_type() == CoprocessorProto::Request_Hello ? static_cast<const CoprocessorProto::Hello *>(message()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MESSAGE_TYPE, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           VerifyRequest(verifier, message(), message_type()) &&
           verifier.EndTable();
  }
};

template<> inline const CoprocessorProto::Heartbeat *RequestEnvelope::message_as<CoprocessorProto::Heartbeat>() const {
  return message_as_Heartbeat();
}

template<> inline const CoprocessorProto::WifiConnectRequest *RequestEnvelope::message_as<CoprocessorProto::WifiConnectRequest>() const {
  return message_as_WifiConnectRequest();
}

template<> inline const CoprocessorProto::StartProvisioning *RequestEnvelope::message_as<CoprocessorProto::StartProvisioning>() const {
  return message_as_StartProvisioning();
}

template<> inline const CoprocessorProto::StopProvisioning *RequestEnvelope::message_as<CoprocessorProto::StopProvisioning>() const {
  return message_as_StopProvisioning();
}

template<> inline const CoprocessorProto::StreamChunk *RequestEnvelope::message_as<CoprocessorProto::StreamChunk>() const {
  return message_as_StreamChunk();
}

template<> inline const CoprocessorProto::Hello *RequestEnvelope::message_as<CoprocessorProto::Hello>() const {
  return message_as_Hello();
}

struct RequestEnvelopeBuilder {
  typedef RequestEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message_type(CoprocessorProto::Request message_type) {
    fbb_.AddElement<uint8_t>(RequestEnvelope::VT_MESSAGE_TYPE, static_cast<uint8_t>(message_type), 0);
  }
  void add_message(::flatbuffers::Offset<void> message) {
    fbb_.AddOffset(RequestEnvelope::VT_MESSAGE, message);
  }
  explicit RequestEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RequestEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RequestEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RequestEnvelope> CreateRequestEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    CoprocessorProto::Request message_type = CoprocessorProto::Request_NONE,
    ::flatbuffers::Offset<void> message = 0) {
  RequestEnvelopeBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_message_type(message_type);
  return builder_.Finish();
}

struct ResponseEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResponseEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE_TYPE = 4,
    VT_MESSAGE = 6
  };
  CoprocessorProto::Response message_type() const {
    return static_cast<CoprocessorProto::Response>(GetField<uint8_t>(VT_MESSAGE_TYPE, 0));
  }
  const void *message() const {
    return GetPointer<const void *>(VT_MESSAGE);
  }
  template<typename T> const T *message_as() const;
  const CoprocessorProto::Heartbeat *message_as_Heartbeat() const {
    return message_type() == CoprocessorProto::Response_Heartbeat ? static_cast<const CoprocessorProto::Heartbeat *>(message()) : nullptr;
  }
  const CoprocessorProto::WifiStatus *message_as_WifiStatus() const {
    return message_type() == CoprocessorProto::Response_WifiStatus ? static_cast<const CoprocessorProto::WifiStatus *>(message()) : nullptr;
  }
  const CoprocessorProto::ProvisioningStatus *message_as_ProvisioningStatus() const {
    return message_type() == CoprocessorProto::Response_ProvisioningStatus ? static_cast<const CoprocessorProto::ProvisioningStatus *>(message()) : nullptr;
  }
  const CoprocessorProto::StreamChunk *message_as_StreamChunk() const {
    return message_type() == CoprocessorProto::Response_StreamChunk ? static_cast<const CoprocessorProto::StreamChunk *>(message()) : nullptr;
  }
  const CoprocessorProto::Hello *message_as_Hello() const {
    return message_type() == CoprocessorProto::Response_Hello ? static_cast<const CoprocessorProto::Hello *>(message()) : nullptr;
  }
  const CoprocessorProto::TimeSync *message_as_TimeSync() const {
    return message_type() == CoprocessorProto::Response_TimeSync ? static_cast<const CoprocessorProto::TimeSync *>(message()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MESSAGE_TYPE, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           VerifyResponse(verifier, message(), message_type()) &&
           verifier.EndTable();
  }
};

template<> inline const CoprocessorProto::Heartbeat *ResponseEnvelope::message_as<CoprocessorProto::Heartbeat>() const {
  return message_as_Heartbeat();
}

template<> inline const CoprocessorProto::WifiStatus *ResponseEnvelope::message_as<CoprocessorProto::WifiStatus>() const {
  return message_as_WifiStatus();
}

template<> inline const CoprocessorProto::ProvisioningStatus *ResponseEnvelope::message_as<CoprocessorProto::ProvisioningStatus>() const {
  return message_as_ProvisioningStatus();
}

template<> inline const CoprocessorProto::StreamChunk *ResponseEnvelope::message_as<CoprocessorProto::StreamChunk>() const {
  return message_as_StreamChunk();
}

template<> inline const CoprocessorProto::Hello *ResponseEnvelope::message_as<CoprocessorProto::Hello>() const {
  return message_as_Hello();
}

template<> inline const CoprocessorProto::TimeSync *ResponseEnvelope::message_as<CoprocessorProto::TimeSync>() const {
  return message_as_TimeSync();
}

struct ResponseEnvelopeBuilder {
  typedef ResponseEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message_type(CoprocessorProto::Response message_type) {
    fbb_.AddElement<uint8_t>(ResponseEnvelope::VT_MESSAGE_TYPE, static_cast<uint8_t>(message_type), 0);
  }
  void add_message(::flatbuffers::Offset<void> message) {
    fbb_.AddOffset(ResponseEnvelope::VT_MESSAGE, message);
  }
  explicit ResponseEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResponseEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResponseEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ResponseEnvelope> CreateResponseEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    CoprocessorProto::Response message_type = CoprocessorProto::Response_NONE,
    ::flatbuffers::Offset<void> message = 0) {
  ResponseEnvelopeBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_message_type(message_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyRequest(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Request type) {
  switch (type) {
    case Request_NONE: {
      return true;
    }
    case Request_Heartbeat: {
      auto ptr = reinterpret_cast<const CoprocessorProto::Heartbeat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Request_WifiConnectRequest: {
      auto ptr = reinterpret_cast<const CoprocessorProto::WifiConnectRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Request_StartProvisioning: {
      auto ptr = reinterpret_cast<const CoprocessorProto::StartProvisioning *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Request_StopProvisioning: {
      auto ptr = reinterpret_cast<const CoprocessorProto::StopProvisioning *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Request_StreamChunk: {
      auto ptr = reinterpret_cast<const CoprocessorProto::StreamChunk *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Request_Hello: {
      auto ptr = reinterpret_cast<const CoprocessorProto::Hello *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyRequestVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRequest(
        verifier,  values->Get(i), types->GetEnum<Request>(i))) {
      return false;
    }
  }
  return true;
}

template <bool B>
inline bool VerifyResponse(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Response type) {
  switch (type) {
    case Response_NONE: {
      return true;
    }
    case Response_Heartbeat: {
      auto ptr = reinterpret_cast<const CoprocessorProto::Heartbeat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Response_WifiStatus: {
      auto ptr = reinterpret_cast<const CoprocessorProto::WifiStatus *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Response_ProvisioningStatus: {
      auto ptr = reinterpret_cast<const CoprocessorProto::ProvisioningStatus *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Response_StreamChunk: {
      auto ptr = reinterpret_cast<const CoprocessorProto::StreamChunk *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Response_Hello: {
      auto ptr = reinterpret_cast<const CoprocessorProto::Hello *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Response_TimeSync: {
      auto ptr = reinterpret_cast<const CoprocessorProto::TimeSync *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyResponseVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyResponse(
        verifier,  values->Get(i), types->GetEnum<Response>(i))) {
      return false;
    }
  }
  return true;
}

inline const CoprocessorProto::RequestEnvelope *GetRequestEnvelope(const void *buf) {
  return ::flatbuffers::GetRoot<CoprocessorProto::RequestEnvelope>(buf);
}

inline const CoprocessorProto::RequestEnvelope *GetSizePrefixedRequestEnvelope(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<CoprocessorProto::RequestEnvelope>(buf);
}

template <bool B = false>
inline bool VerifyRequestEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<CoprocessorProto::RequestEnvelope>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedRequestEnvelopeBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<CoprocessorProto::RequestEnvelope>(nullptr);
}

inline void FinishRequestEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CoprocessorProto::RequestEnvelope> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRequestEnvelopeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<CoprocessorProto::RequestEnvelope> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace CoprocessorProto

#endif  // FLATBUFFERS_GENERATED_COPROCESSOR_COPROCESSORPROTO_H_
