// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MEDIA_COPROCESSORPROTO_MEDIA_H_
#define FLATBUFFERS_GENERATED_MEDIA_COPROCESSORPROTO_MEDIA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace CoprocessorProto {
namespace Media {

struct Action;
struct ActionBuilder;

struct VolumeCommand;
struct VolumeCommandBuilder;

struct Subscribe;
struct SubscribeBuilder;

struct UnsubscribeAll;
struct UnsubscribeAllBuilder;

struct GetTopology;
struct GetTopologyBuilder;

struct TrackMetadata;
struct TrackMetadataBuilder;

struct StateUpdate;
struct StateUpdateBuilder;

struct Member;
struct MemberBuilder;

struct Group;
struct GroupBuilder;

struct TopologyUpdate;
struct TopologyUpdateBuilder;

enum TransportState : uint8_t {
  TransportState_Stopped = 0,
  TransportState_Playing = 1,
  TransportState_Paused = 2,
  TransportState_Transitioning = 3,
  TransportState_MIN = TransportState_Stopped,
  TransportState_MAX = TransportState_Transitioning
};

inline const TransportState (&EnumValuesTransportState())[4] {
  static const TransportState values[] = {
    TransportState_Stopped,
    TransportState_Playing,
    TransportState_Paused,
    TransportState_Transitioning
  };
  return values;
}

inline const char * const *EnumNamesTransportState() {
  static const char * const names[5] = {
    "Stopped",
    "Playing",
    "Paused",
    "Transitioning",
    nullptr
  };
  return names;
}

inline const char *EnumNameTransportState(TransportState e) {
  if (::flatbuffers::IsOutRange(e, TransportState_Stopped, TransportState_Transitioning)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTransportState()[index];
}

enum ActionType : uint8_t {
  ActionType_Play = 0,
  ActionType_Pause = 1,
  ActionType_TogglePlayPause = 2,
  ActionType_Next = 3,
  ActionType_Previous = 4,
  ActionType_Stop = 5,
  ActionType_MIN = ActionType_Play,
  ActionType_MAX = ActionType_Stop
};

inline const ActionType (&EnumValuesActionType())[6] {
  static const ActionType values[] = {
    ActionType_Play,
    ActionType_Pause,
    ActionType_TogglePlayPause,
    ActionType_Next,
    ActionType_Previous,
    ActionType_Stop
  };
  return values;
}

inline const char * const *EnumNamesActionType() {
  static const char * const names[7] = {
    "Play",
    "Pause",
    "TogglePlayPause",
    "Next",
    "Previous",
    "Stop",
    nullptr
  };
  return names;
}

inline const char *EnumNameActionType(ActionType e) {
  if (::flatbuffers::IsOutRange(e, ActionType_Play, ActionType_Stop)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesActionType()[index];
}

struct Action FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENDPOINT_IP = 4,
    VT_ENDPOINT_PORT = 6,
    VT_ACTION = 8
  };
  const ::flatbuffers::String *endpoint_ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENDPOINT_IP);
  }
  uint16_t endpoint_port() const {
    return GetField<uint16_t>(VT_ENDPOINT_PORT, 1400);
  }
  CoprocessorProto::Media::ActionType action() const {
    return static_cast<CoprocessorProto::Media::ActionType>(GetField<uint8_t>(VT_ACTION, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENDPOINT_IP) &&
           verifier.VerifyString(endpoint_ip()) &&
           VerifyField<uint16_t>(verifier, VT_ENDPOINT_PORT, 2) &&
           VerifyField<uint8_t>(verifier, VT_ACTION, 1) &&
           verifier.EndTable();
  }
};

struct ActionBuilder {
  typedef Action Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_endpoint_ip(::flatbuffers::Offset<::flatbuffers::String> endpoint_ip) {
    fbb_.AddOffset(Action::VT_ENDPOINT_IP, endpoint_ip);
  }
  void add_endpoint_port(uint16_t endpoint_port) {
    fbb_.AddElement<uint16_t>(Action::VT_ENDPOINT_PORT, endpoint_port, 1400);
  }
  void add_action(CoprocessorProto::Media::ActionType action) {
    fbb_.AddElement<uint8_t>(Action::VT_ACTION, static_cast<uint8_t>(action), 0);
  }
  explicit ActionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Action> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Action>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Action> CreateAction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> endpoint_ip = 0,
    uint16_t endpoint_port = 1400,
    CoprocessorProto::Media::ActionType action = CoprocessorProto::Media::ActionType_Play) {
  ActionBuilder builder_(_fbb);
  builder_.add_endpoint_ip(endpoint_ip);
  builder_.add_endpoint_port(endpoint_port);
  builder_.add_action(action);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Action> CreateActionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *endpoint_ip = nullptr,
    uint16_t endpoint_port = 1400,
    CoprocessorProto::Media::ActionType action = CoprocessorProto::Media::ActionType_Play) {
  auto endpoint_ip__ = endpoint_ip ? _fbb.CreateString(endpoint_ip) : 0;
  return CoprocessorProto::Media::CreateAction(
      _fbb,
      endpoint_ip__,
      endpoint_port,
      action);
}

struct VolumeCommand FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VolumeCommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENDPOINT_IP = 4,
    VT_ENDPOINT_PORT = 6,
    VT_VOLUME = 8,
    VT_IS_RELATIVE = 10
  };
  const ::flatbuffers::String *endpoint_ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENDPOINT_IP);
  }
  uint16_t endpoint_port() const {
    return GetField<uint16_t>(VT_ENDPOINT_PORT, 1400);
  }
  int16_t volume() const {
    return GetField<int16_t>(VT_VOLUME, 0);
  }
  bool is_relative() const {
    return GetField<uint8_t>(VT_IS_RELATIVE, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENDPOINT_IP) &&
           verifier.VerifyString(endpoint_ip()) &&
           VerifyField<uint16_t>(verifier, VT_ENDPOINT_PORT, 2) &&
           VerifyField<int16_t>(verifier, VT_VOLUME, 2) &&
           VerifyField<uint8_t>(verifier, VT_IS_RELATIVE, 1) &&
           verifier.EndTable();
  }
};

struct VolumeCommandBuilder {
  typedef VolumeCommand Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_endpoint_ip(::flatbuffers::Offset<::flatbuffers::String> endpoint_ip) {
    fbb_.AddOffset(VolumeCommand::VT_ENDPOINT_IP, endpoint_ip);
  }
  void add_endpoint_port(uint16_t endpoint_port) {
    fbb_.AddElement<uint16_t>(VolumeCommand::VT_ENDPOINT_PORT, endpoint_port, 1400);
  }
  void add_volume(int16_t volume) {
    fbb_.AddElement<int16_t>(VolumeCommand::VT_VOLUME, volume, 0);
  }
  void add_is_relative(bool is_relative) {
    fbb_.AddElement<uint8_t>(VolumeCommand::VT_IS_RELATIVE, static_cast<uint8_t>(is_relative), 0);
  }
  explicit VolumeCommandBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VolumeCommand> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VolumeCommand>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VolumeCommand> CreateVolumeCommand(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> endpoint_ip = 0,
    uint16_t endpoint_port = 1400,
    int16_t volume = 0,
    bool is_relative = false) {
  VolumeCommandBuilder builder_(_fbb);
  builder_.add_endpoint_ip(endpoint_ip);
  builder_.add_volume(volume);
  builder_.add_endpoint_port(endpoint_port);
  builder_.add_is_relative(is_relative);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VolumeCommand> CreateVolumeCommandDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *endpoint_ip = nullptr,
    uint16_t endpoint_port = 1400,
    int16_t volume = 0,
    bool is_relative = false) {
  auto endpoint_ip__ = endpoint_ip ? _fbb.CreateString(endpoint_ip) : 0;
  return CoprocessorProto::Media::CreateVolumeCommand(
      _fbb,
      endpoint_ip__,
      endpoint_port,
      volume,
      is_relative);
}

struct Subscribe FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubscribeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENDPOINT_IP = 4,
    VT_ENDPOINT_PORT = 6
  };
  const ::flatbuffers::String *endpoint_ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENDPOINT_IP);
  }
  uint16_t endpoint_port() const {
    return GetField<uint16_t>(VT_ENDPOINT_PORT, 1400);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENDPOINT_IP) &&
           verifier.VerifyString(endpoint_ip()) &&
           VerifyField<uint16_t>(verifier, VT_ENDPOINT_PORT, 2) &&
           verifier.EndTable();
  }
};

struct SubscribeBuilder {
  typedef Subscribe Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_endpoint_ip(::flatbuffers::Offset<::flatbuffers::String> endpoint_ip) {
    fbb_.AddOffset(Subscribe::VT_ENDPOINT_IP, endpoint_ip);
  }
  void add_endpoint_port(uint16_t endpoint_port) {
    fbb_.AddElement<uint16_t>(Subscribe::VT_ENDPOINT_PORT, endpoint_port, 1400);
  }
  explicit SubscribeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Subscribe> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Subscribe>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Subscribe> CreateSubscribe(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> endpoint_ip = 0,
    uint16_t endpoint_port = 1400) {
  SubscribeBuilder builder_(_fbb);
  builder_.add_endpoint_ip(endpoint_ip);
  builder_.add_endpoint_port(endpoint_port);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Subscribe> CreateSubscribeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *endpoint_ip = nullptr,
    uint16_t endpoint_port = 1400) {
  auto endpoint_ip__ = endpoint_ip ? _fbb.CreateString(endpoint_ip) : 0;
  return CoprocessorProto::Media::CreateSubscribe(
      _fbb,
      endpoint_ip__,
      endpoint_port);
}

struct UnsubscribeAll FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UnsubscribeAllBuilder Builder;
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct UnsubscribeAllBuilder {
  typedef UnsubscribeAll Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit UnsubscribeAllBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UnsubscribeAll> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UnsubscribeAll>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UnsubscribeAll> CreateUnsubscribeAll(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  UnsubscribeAllBuilder builder_(_fbb);
  return builder_.Finish();
}

struct GetTopology FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetTopologyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEED_IP = 4,
    VT_SEED_PORT = 6
  };
  const ::flatbuffers::String *seed_ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SEED_IP);
  }
  uint16_t seed_port() const {
    return GetField<uint16_t>(VT_SEED_PORT, 1400);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SEED_IP) &&
           verifier.VerifyString(seed_ip()) &&
           VerifyField<uint16_t>(verifier, VT_SEED_PORT, 2) &&
           verifier.EndTable();
  }
};

struct GetTopologyBuilder {
  typedef GetTopology Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seed_ip(::flatbuffers::Offset<::flatbuffers::String> seed_ip) {
    fbb_.AddOffset(GetTopology::VT_SEED_IP, seed_ip);
  }
  void add_seed_port(uint16_t seed_port) {
    fbb_.AddElement<uint16_t>(GetTopology::VT_SEED_PORT, seed_port, 1400);
  }
  explicit GetTopologyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetTopology> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetTopology>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetTopology> CreateGetTopology(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> seed_ip = 0,
    uint16_t seed_port = 1400) {
  GetTopologyBuilder builder_(_fbb);
  builder_.add_seed_ip(seed_ip);
  builder_.add_seed_port(seed_port);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GetTopology> CreateGetTopologyDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *seed_ip = nullptr,
    uint16_t seed_port = 1400) {
  auto seed_ip__ = seed_ip ? _fbb.CreateString(seed_ip) : 0;
  return CoprocessorProto::Media::CreateGetTopology(
      _fbb,
      seed_ip__,
      seed_port);
}

struct TrackMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrackMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TITLE = 4,
    VT_ARTIST = 6,
    VT_ALBUM = 8,
    VT_DURATION_SECONDS = 10,
    VT_ELAPSED_SECONDS = 12
  };
  const ::flatbuffers::String *title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TITLE);
  }
  const ::flatbuffers::String *artist() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ARTIST);
  }
  const ::flatbuffers::String *album() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALBUM);
  }
  ::flatbuffers::Optional<uint32_t> duration_seconds() const {
    return GetOptional<uint32_t, uint32_t>(VT_DURATION_SECONDS);
  }
  ::flatbuffers::Optional<uint32_t> elapsed_seconds() const {
    return GetOptional<uint32_t, uint32_t>(VT_ELAPSED_SECONDS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TITLE) &&
           verifier.VerifyString(title()) &&
           VerifyOffset(verifier, VT_ARTIST) &&
           verifier.VerifyString(artist()) &&
           VerifyOffset(verifier, VT_ALBUM) &&
           verifier.VerifyString(album()) &&
           VerifyField<uint32_t>(verifier, VT_DURATION_SECONDS, 4) &&
           VerifyField<uint32_t>(verifier, VT_ELAPSED_SECONDS, 4) &&
           verifier.EndTable();
  }
};

struct TrackMetadataBuilder {
  typedef TrackMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_title(::flatbuffers::Offset<::flatbuffers::String> title) {
    fbb_.AddOffset(TrackMetadata::VT_TITLE, title);
  }
  void add_artist(::flatbuffers::Offset<::flatbuffers::String> artist) {
    fbb_.AddOffset(TrackMetadata::VT_ARTIST, artist);
  }
  void add_album(::flatbuffers::Offset<::flatbuffers::String> album) {
    fbb_.AddOffset(TrackMetadata::VT_ALBUM, album);
  }
  void add_duration_seconds(uint32_t duration_seconds) {
    fbb_.AddElement<uint32_t>(TrackMetadata::VT_DURATION_SECONDS, duration_seconds);
  }
  void add_elapsed_seconds(uint32_t elapsed_seconds) {
    fbb_.AddElement<uint32_t>(TrackMetadata::VT_ELAPSED_SECONDS, elapsed_seconds);
  }
  explicit TrackMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrackMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrackMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TrackMetadata> CreateTrackMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> title = 0,
    ::flatbuffers::Offset<::flatbuffers::String> artist = 0,
    ::flatbuffers::Offset<::flatbuffers::String> album = 0,
    ::flatbuffers::Optional<uint32_t> duration_seconds = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint32_t> elapsed_seconds = ::flatbuffers::nullopt) {
  TrackMetadataBuilder builder_(_fbb);
  if(elapsed_seconds) { builder_.add_elapsed_seconds(*elapsed_seconds); }
  if(duration_seconds) { builder_.add_duration_seconds(*duration_seconds); }
  builder_.add_album(album);
  builder_.add_artist(artist);
  builder_.add_title(title);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrackMetadata> CreateTrackMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *title = nullptr,
    const char *artist = nullptr,
    const char *album = nullptr,
    ::flatbuffers::Optional<uint32_t> duration_seconds = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint32_t> elapsed_seconds = ::flatbuffers::nullopt) {
  auto title__ = title ? _fbb.CreateString(title) : 0;
  auto artist__ = artist ? _fbb.CreateString(artist) : 0;
  auto album__ = album ? _fbb.CreateString(album) : 0;
  return CoprocessorProto::Media::CreateTrackMetadata(
      _fbb,
      title__,
      artist__,
      album__,
      duration_seconds,
      elapsed_seconds);
}

struct StateUpdate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StateUpdateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENDPOINT_IP = 4,
    VT_TRANSPORT_STATE = 6,
    VT_VOLUME = 8,
    VT_IS_MUTED = 10,
    VT_TRACK = 12
  };
  const ::flatbuffers::String *endpoint_ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENDPOINT_IP);
  }
  ::flatbuffers::Optional<CoprocessorProto::Media::TransportState> transport_state() const {
    return GetOptional<uint8_t, CoprocessorProto::Media::TransportState>(VT_TRANSPORT_STATE);
  }
  ::flatbuffers::Optional<uint8_t> volume() const {
    return GetOptional<uint8_t, uint8_t>(VT_VOLUME);
  }
  ::flatbuffers::Optional<bool> is_muted() const {
    return GetOptional<uint8_t, bool>(VT_IS_MUTED);
  }
  const CoprocessorProto::Media::TrackMetadata *track() const {
    return GetPointer<const CoprocessorProto::Media::TrackMetadata *>(VT_TRACK);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENDPOINT_IP) &&
           verifier.VerifyString(endpoint_ip()) &&
           VerifyField<uint8_t>(verifier, VT_TRANSPORT_STATE, 1) &&
           VerifyField<uint8_t>(verifier, VT_VOLUME, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_MUTED, 1) &&
           VerifyOffset(verifier, VT_TRACK) &&
           verifier.VerifyTable(track()) &&
           verifier.EndTable();
  }
};

struct StateUpdateBuilder {
  typedef StateUpdate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_endpoint_ip(::flatbuffers::Offset<::flatbuffers::String> endpoint_ip) {
    fbb_.AddOffset(StateUpdate::VT_ENDPOINT_IP, endpoint_ip);
  }
  void add_transport_state(CoprocessorProto::Media::TransportState transport_state) {
    fbb_.AddElement<uint8_t>(StateUpdate::VT_TRANSPORT_STATE, static_cast<uint8_t>(transport_state));
  }
  void add_volume(uint8_t volume) {
    fbb_.AddElement<uint8_t>(StateUpdate::VT_VOLUME, volume);
  }
  void add_is_muted(bool is_muted) {
    fbb_.AddElement<uint8_t>(StateUpdate::VT_IS_MUTED, static_cast<uint8_t>(is_muted));
  }
  void add_track(::flatbuffers::Offset<CoprocessorProto::Media::TrackMetadata> track) {
    fbb_.AddOffset(StateUpdate::VT_TRACK, track);
  }
  explicit StateUpdateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StateUpdate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StateUpdate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StateUpdate> CreateStateUpdate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> endpoint_ip = 0,
    ::flatbuffers::Optional<CoprocessorProto::Media::TransportState> transport_state = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint8_t> volume = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<bool> is_muted = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<CoprocessorProto::Media::TrackMetadata> track = 0) {
  StateUpdateBuilder builder_(_fbb);
  builder_.add_track(track);
  builder_.add_endpoint_ip(endpoint_ip);
  if(is_muted) { builder_.add_is_muted(*is_muted); }
  if(volume) { builder_.add_volume(*volume); }
  if(transport_state) { builder_.add_transport_state(*transport_state); }
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StateUpdate> CreateStateUpdateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *endpoint_ip = nullptr,
    ::flatbuffers::Optional<CoprocessorProto::Media::TransportState> transport_state = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<uint8_t> volume = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<bool> is_muted = ::flatbuffers::nullopt,
    ::flatbuffers::Offset<CoprocessorProto::Media::TrackMetadata> track = 0) {
  auto endpoint_ip__ = endpoint_ip ? _fbb.CreateString(endpoint_ip) : 0;
  return CoprocessorProto::Media::CreateStateUpdate(
      _fbb,
      endpoint_ip__,
      transport_state,
      volume,
      is_muted,
      track);
}

struct Member FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MemberBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_UUID = 6,
    VT_IP = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *uuid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UUID);
  }
  const ::flatbuffers::String *ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IP);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_UUID) &&
           verifier.VerifyString(uuid()) &&
           VerifyOffset(verifier, VT_IP) &&
           verifier.VerifyString(ip()) &&
           verifier.EndTable();
  }
};

struct MemberBuilder {
  typedef Member Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Member::VT_NAME, name);
  }
  void add_uuid(::flatbuffers::Offset<::flatbuffers::String> uuid) {
    fbb_.AddOffset(Member::VT_UUID, uuid);
  }
  void add_ip(::flatbuffers::Offset<::flatbuffers::String> ip) {
    fbb_.AddOffset(Member::VT_IP, ip);
  }
  explicit MemberBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Member> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Member>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Member> CreateMember(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> uuid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ip = 0) {
  MemberBuilder builder_(_fbb);
  builder_.add_ip(ip);
  builder_.add_uuid(uuid);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Member> CreateMemberDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *uuid = nullptr,
    const char *ip = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto uuid__ = uuid ? _fbb.CreateString(uuid) : 0;
  auto ip__ = ip ? _fbb.CreateString(ip) : 0;
  return CoprocessorProto::Media::CreateMember(
      _fbb,
      name__,
      uuid__,
      ip__);
}

struct Group FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_NAME = 6,
    VT_COORDINATOR_IP = 8,
    VT_COORDINATOR_PORT = 10,
    VT_IS_PLAYING = 12,
    VT_MEMBERS = 14
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *coordinator_ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COORDINATOR_IP);
  }
  uint16_t coordinator_port() const {
    return GetField<uint16_t>(VT_COORDINATOR_PORT, 1400);
  }
  bool is_playing() const {
    return GetField<uint8_t>(VT_IS_PLAYING, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<CoprocessorProto::Media::Member>> *members() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<CoprocessorProto::Media::Member>> *>(VT_MEMBERS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_COORDINATOR_IP) &&
           verifier.VerifyString(coordinator_ip()) &&
           VerifyField<uint16_t>(verifier, VT_COORDINATOR_PORT, 2) &&
           VerifyField<uint8_t>(verifier, VT_IS_PLAYING, 1) &&
           VerifyOffset(verifier, VT_MEMBERS) &&
           verifier.VerifyVector(members()) &&
           verifier.VerifyVectorOfTables(members()) &&
           verifier.EndTable();
  }
};

struct GroupBuilder {
  typedef Group Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(Group::VT_ID, id);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Group::VT_NAME, name);
  }
  void add_coordinator_ip(::flatbuffers::Offset<::flatbuffers::String> coordinator_ip) {
    fbb_.AddOffset(Group::VT_COORDINATOR_IP, coordinator_ip);
  }
  void add_coordinator_port(uint16_t coordinator_port) {
    fbb_.AddElement<uint16_t>(Group::VT_COORDINATOR_PORT, coordinator_port, 1400);
  }
  void add_is_playing(bool is_playing) {
    fbb_.AddElement<uint8_t>(Group::VT_IS_PLAYING, static_cast<uint8_t>(is_playing), 0);
  }
  void add_members(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<CoprocessorProto::Media::Member>>> members) {
    fbb_.AddOffset(Group::VT_MEMBERS, members);
  }
  explicit GroupBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Group> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Group>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Group> CreateGroup(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> coordinator_ip = 0,
    uint16_t coordinator_port = 1400,
    bool is_playing = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<CoprocessorProto::Media::Member>>> members = 0) {
  GroupBuilder builder_(_fbb);
  builder_.add_members(members);
  builder_.add_coordinator_ip(coordinator_ip);
  builder_.add_name(name);
  builder_.add_id(id);
  builder_.add_coordinator_port(coordinator_port);
  builder_.add_is_playing(is_playing);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Group> CreateGroupDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *name = nullptr,
    const char *coordinator_ip = nullptr,
    uint16_t coordinator_port = 1400,
    bool is_playing = false,
    const std::vector<::flatbuffers::Offset<CoprocessorProto::Media::Member>> *members = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto coordinator_ip__ = coordinator_ip ? _fbb.CreateString(coordinator_ip) : 0;
  auto members__ = members ? _fbb.CreateVector<::flatbuffers::Offset<CoprocessorProto::Media::Member>>(*members) : 0;
  return CoprocessorProto::Media::CreateGroup(
      _fbb,
      id__,
      name__,
      coordinator_ip__,
      coordinator_port,
      is_playing,
      members__);
}

struct TopologyUpdate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TopologyUpdateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GROUPS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<CoprocessorProto::Media::Group>> *groups() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<CoprocessorProto::Media::Group>> *>(VT_GROUPS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GROUPS) &&
           verifier.VerifyVector(groups()) &&
           verifier.VerifyVectorOfTables(groups()) &&
           verifier.EndTable();
  }
};

struct TopologyUpdateBuilder {
  typedef TopologyUpdate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_groups(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<CoprocessorProto::Media::Group>>> groups) {
    fbb_.AddOffset(TopologyUpdate::VT_GROUPS, groups);
  }
  explicit TopologyUpdateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TopologyUpdate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TopologyUpdate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TopologyUpdate> CreateTopologyUpdate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<CoprocessorProto::Media::Group>>> groups = 0) {
  TopologyUpdateBuilder builder_(_fbb);
  builder_.add_groups(groups);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TopologyUpdate> CreateTopologyUpdateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<CoprocessorProto::Media::Group>> *groups = nullptr) {
  auto groups__ = groups ? _fbb.CreateVector<::flatbuffers::Offset<CoprocessorProto::Media::Group>>(*groups) : 0;
  return CoprocessorProto::Media::CreateTopologyUpdate(
      _fbb,
      groups__);
}

}  // namespace Media
}  // namespace CoprocessorProto

#endif  // FLATBUFFERS_GENERATED_MEDIA_COPROCESSORPROTO_MEDIA_H_
